config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      devise_scope :user do
        scope :users do
          post :sign_in, to: 'sessions#create'
        end
      end

      resources :sections, only: :index
      resources :lessons, only: :show

      resources :lesson_units, only: [] do
        post :pass, on: :member
      end
    end
  end

  namespace :admin do
    resources :sections
    resources :lessons do
      resources :lesson_units, only: %i[create update destroy]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :section

  has_many :lesson_units
  has_many :user_progress_states, as: :learn_unit, dependent: :destroy

  validates :name, :description, :order, presence: true
  validates :order, uniqueness: { scope: :section_id }
end

app/models/lesson_unit.rb
class LessonUnit < ApplicationRecord
  belongs_to :lesson

  has_many :user_progress_states, as: :learn_unit, dependent: :destroy

  validates :content_block, :order, presence: true
  validates :order, uniqueness: { scope: :lesson_id }

  def passed?(user)
    user_progress_states.exists?(user:, state: 1)
  end
end

app/models/section.rb
class Section < ApplicationRecord
  has_many :lessons

  validates :name, :order, presence: true
  validates :order, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :user_progress_states, dependent: :destroy

  def generate_jwt
    JWT.encode(
      { id: id, exp: 60.days.from_now.to_i },
      Rails.application.secrets.secret_key_base || ENV['SECRET_KEY_BASE']
    )
  end
end

app/models/user_progress_state.rb
class UserProgressState < ApplicationRecord
  belongs_to :user
  belongs_to :learn_unit, polymorphic: true

  enum state: { passed: 1 }

  validates :state, presence: true
  validates :user_id, uniqueness: { scope: %i[learn_unit_id learn_unit_type] }
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'admin_application'

  protect_from_forgery prepend: true
  before_action :authenticate_user!
end

app/controllers/admin/lesson_units_controller.rb
class Admin::LessonUnitsController < Admin::BaseController
  before_action :set_lesson_unit, only: %i[show edit update destroy]
  before_action :set_lesson, only: %i[create]

  def create
    @lesson_unit = LessonUnit.new(lesson_params) do |lesson_unit|
      lesson_unit.order = LessonUnit.maximum(:order).to_i + 1
      lesson_unit.lesson = @lesson
    end

    respond_to do |format|
      if @lesson_unit.save
        format.html { redirect_to(admin_lesson_path(@lesson_unit.lesson), notice: 'Lesson unit was successfully created.') }
      else
        # TODO: make it works
        # format.html { render(:new, status: :unprocessable_entity) }
      end
    end
  end

  def update
    respond_to do |format|
      if @lesson_unit.update(lesson_params)
        format.html { redirect_to(admin_lesson_path(@lesson_unit.lesson), notice: 'Lesson unit was successfully updated.') }
      else
        # TODO: make it works
        # format.html { render(:edit, status: :unprocessable_entity) }
      end
    end
  end

  def destroy
    @lesson_unit.destroy

    respond_to do |format|
      format.html { redirect_to(admin_lesson_path(@lesson_unit.lesson), notice: 'Lesson unit was successfully destroyed.') }
    end
  end

  private

  def set_lesson
    @lesson = Lesson.find(params[:lesson_id])
  end

  def set_lesson_unit
    @lesson_unit = LessonUnit.find(params[:id])
  end

  def lesson_params
    params.require('lesson_unit').permit(:content_block, :order)
  end
end

app/controllers/admin/lessons_controller.rb
class Admin::LessonsController < Admin::BaseController
  before_action :set_lesson, only: %i[show edit update destroy]

  def index
    @lessons = Lesson.all.order(:section_id, :order)
  end

  def show; end

  def new
    @lesson = Lesson.new
  end

  def edit; end

  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to(admin_lesson_path(@lesson), notice: 'Lesson was successfully created.') }
      else
        format.html { render(:new, status: :unprocessable_entity) }
      end
    end
  end

  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to(admin_lesson_path(@lesson), notice: 'Lesson was successfully updated.') }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
      end
    end
  end

  def destroy
    @lesson.destroy

    respond_to do |format|
      format.html { redirect_to(admin_lessons_path, notice: 'Lesson was successfully destroyed.') }
    end
  end

  private

  def set_lesson
    @lesson = Lesson.find(params[:id])
  end

  def lesson_params
    params.require('lesson').permit(:name, :description, :order, :section_id)
  end
end

app/controllers/admin/sections_controller.rb
class Admin::SectionsController < Admin::BaseController
  before_action :set_section, only: %i[show edit update destroy]

  def index
    @sections = Section.all
  end

  def show; end

  def new
    @section = Section.new
  end

  def edit; end

  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to(admin_section_path(@section), notice: 'Section was successfully created.') }
      else
        format.html { render(:new, status: :unprocessable_entity) }
      end
    end
  end

  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to(admin_section_path(@section), notice: 'Section was successfully updated.') }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
      end
    end
  end

  def destroy
    @section.destroy

    respond_to do |format|
      format.html { redirect_to(admin_sections_path, notice: 'Section was successfully destroyed.') }
    end
  end

  private

  def set_section
    @section = Section.find(params[:id])
  end

  def section_params
    params.require('section').permit(:name, :description, :order)
  end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  before_action :parse_token, :authenticate_user!

  private

  def parse_token
    return if request.headers['Authorization'].blank?

    authenticate_or_request_with_http_token do |token|
      jwt_payload = JWT.decode(token, Rails.application.secrets.secret_key_base || ENV['SECRET_KEY_BASE']).first

      @current_user_id = jwt_payload['id'] || 1
    rescue JWT::ExpiredSignature, JWT::VerificationError, JWT::DecodeError
      head(:unauthorized)
    end
  end

  def authenticate_user!
    head(:unauthorized) unless signed_in?
  end

  def current_user
    @current_user ||= super || User.find(@current_user_id)
  end

  def signed_in?
    @current_user_id.present?
  end
end

app/controllers/api/v1/lesson_units_controller.rb
class Api::V1::LessonUnitsController < Api::V1::BaseController
  protect_from_forgery unless: -> { request.format.json? }

  def pass
    LessonUnit.find(params[:id]).user_progress_states.create!(user: current_user, state: 1)
  end
end

app/controllers/api/v1/lessons_controller.rb
class Api::V1::LessonsController < Api::V1::BaseController
  def show
    @lesson = Lesson.find(params[:id])
  end
end

app/controllers/api/v1/sections_controller.rb
class Api::V1::SectionsController < Api::V1::BaseController
  def index
    @sections = Section.preload(:lessons).all
  end
end

app/controllers/api/v1/sessions_controller.rb
class Api::V1::SessionsController < Devise::SessionsController
  protect_from_forgery unless: -> { request.format.json? }

  def create
    user = User.find_by(email: sign_in_params[:email])

    if !user.nil? && user.valid_password?(sign_in_params[:password])
      @current_user = user
    else
      render(json: { errors: { 'email or password' => ['is invalid'] } }, status: :unprocessable_entity)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/admin/lessons/_form.html.erb
<div class="container-sm">
  <%= form_with(model: lesson, url: url) do |form| %>
    <% if lesson.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(lesson.errors.count, 'error') %> prohibited this section from being saved:</h2>

        <ul>
          <% lesson.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <div class="mb-3">
        <%= form.label(:name, 'Название урока', class: 'form-label') %>
        <%= form.text_field(:name, class: 'form-control') %>
      </div>

      <div class="mb-3">
        <%= form.label(:description, 'Описание урока', class: 'form-label') %>
        <%= form.text_field(:description, class: 'form-control') %>
      </div>

      <div class="mb-3">
        <%= form.label(:order, 'Раздел', class: 'form-label') %>
        <%= form.collection_select(:section_id, Section.all, :id, :name, { prompt: true }, { class: 'form-select' }) %>
      </div>

      <div class="mb-3">
        <%= form.label(:order, 'Порядковый номер', class: 'form-label') %>
        <%= form.text_field(:order, class: 'form-control') %>
      </div>

      <%= form.submit('Отправить', class: 'btn btn-primary') %>
    </div>
  <% end %>
</div>

app/views/admin/lessons/edit.html.erb
<div class="container-fluid">
  <h1>Редактирование урока</h1>

  <%= render('admin/lessons/form', lesson: @lesson, url: admin_lesson_path(@lesson)) %>

  <br>

  <div>
    <%= link_to('Показать урок', admin_lesson_path(@lesson)) %>
  </div>
</div>

app/views/admin/lessons/index.html.erb
<div class="container-fluid">
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>

  <h1>Уроки</h1>

  <%= button_to('Добавить новый урок', new_admin_lesson_path, method: :get, class: 'btn btn-success') %>

  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Название</th>
        <th>Описание</th>
        <th>ID раздела</th>
        <th>Позиция</th>
      </tr>
    </thead>
    <% @lessons.each do |lesson| %>
      <tr>
        <th><%= lesson.id %></th>
        <td><%= link_to(lesson.name, admin_lesson_path(lesson)) %></td>
        <td><%= lesson.description %></td>
        <td><%= lesson.section_id %></td>
        <td><%= lesson.order %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/admin/lessons/new.html.erb
<div class="container-fluid">
  <h1>Новый урок</h1>

  <%= render('admin/lessons/form', lesson: @lesson, url: admin_lessons_path) %>
</div>

app/views/admin/lessons/show.html.erb
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<script>
  tinymce.init({
    selector: '.tinymce',
    height: 500,
    menubar: false,
    plugins: [
      'advlist autolink lists link image charmap print preview anchor',
      'searchreplace visualblocks code fullscreen',
      'insertdatetime media table paste code help wordcount'
    ],
    toolbar: 'undo redo | formatselect | ' +
      ' bold italic backcolor | alignleft aligncenter ' +
      ' alignright alignjustify | bullist numlist outdent indent | ' +
      ' removeformat | help'
  });
</script>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


<div class="container-fluid">
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>

  <div style="display: block">
    <h1 style="display: inline-block"><%= @lesson.name %></h1>
    <%= link_to('Редактировать', edit_admin_lesson_path(@lesson)) %>
    <%= button_to('Удалить', admin_lesson_path(@lesson), method: :delete, class: 'btn btn-danger') %>
  </div>

  <p><b>Описание урока:</b> <%= @lesson.description %></p>

  <p><b>Количество секций в уроке:</b> <%= @lesson.lesson_units.count %></p>

  <% @lesson.lesson_units.order(:order).each do |lesson_unit| %>
    <div style="display: block; margin: 10px 0;">
      <button class='btn btn-primary' data-toggle='modal' data-target='#lessonUnitModal<%= lesson_unit.id %>'>
        Редактировать страницу <%= lesson_unit.order %> урока
      </button>
      <div style="display: inline-block;">
        <%= button_to('Удалить', admin_lesson_lesson_unit_path(@lesson, lesson_unit), method: :delete, class: 'btn btn-danger') %>
      </div>
    </div>

    <div class='modal fade bd-example-modal-lg' id='lessonUnitModal<%= lesson_unit.id %>' tabindex='-1' aria-labelledby='exampleModalLabel' aria-hidden='true'>
      <div class='modal-dialog modal-lg'>
        <div class='modal-content'>
          <div class='modal-header'>
            <h5 class='modal-title' id='exampleModalLabel'>Часть <%= lesson_unit.order %> урока</h5>
            <button type='button' class='close' data-dismiss='modal' aria-label='Close'>
              <span aria-hidden='true'>&times;</span>
            </button>
          </div>
          <%= form_with(model: lesson_unit, url: admin_lesson_lesson_unit_path(@lesson, lesson_unit)) do |form| %>
            <div class='modal-body'>
              <div class="mb-3">
                <%= form.label(:content_block, 'Содержимое секции', class: 'form-label') %>
                <%= form.text_area(:content_block, class: 'tinymce') %>
              </div>
            </div>
            <div>
              <div class='modal-footer'>
                <button type='button' class='btn btn-secondary' data-dismiss='modal'>Закрыть</button>
                <%= form.submit('Сохранить', class: 'btn btn-primary') %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>

  <div style="display: block; margin: 20px 0;">
    <button class='btn btn-success' data-toggle='modal' data-target='#lessonUnitModalNew'>
      Добавить новую страницу
    </button>
  </div>

  <div class='modal fade bd-example-modal-lg' id='lessonUnitModalNew' tabindex='-1' aria-labelledby='exampleModalLabel' aria-hidden='true'>
    <div class='modal-dialog modal-lg'>
      <div class='modal-content'>
        <div class='modal-header'>
          <h5 class='modal-title' id='exampleModalLabel'>Новая часть урока</h5>
          <button type='button' class='close' data-dismiss='modal' aria-label='Close'>
            <span aria-hidden='true'>&times;</span>
          </button>
        </div>
        <%= form_with(model: LessonUnit.new, url: admin_lesson_lesson_units_path(@lesson)) do |form| %>
          <div class='modal-body'>
            <div class="mb-3">
              <%= form.label(:content_block, 'Содержимое секции', class: 'form-label') %>
              <%= form.text_area(:content_block, class: 'tinymce') %>
            </div>
          </div>
          <div class='modal-footer'>
            <button type='button' class='btn btn-secondary' data-dismiss='modal'>Закрыть</button>
            <%= form.submit('Сохранить', class: 'btn btn-primary') %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/sections/_form.html.erb
<div class="container-sm">
  <%= form_with(model: section, url: url) do |form| %>
    <% if section.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(section.errors.count, 'error') %> prohibited this section from being saved:</h2>

        <ul>
          <% section.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <div class="mb-3">
        <%= form.label(:name, 'Название раздела', class: 'form-label') %>
        <%= form.text_field(:name, class: 'form-control') %>
      </div>

      <div class="mb-3">
        <%= form.label(:description, 'Описание раздела', class: 'form-label') %>
        <%= form.text_field(:description, class: 'form-control') %>
      </div>

      <div class="mb-3">
        <%= form.label(:order, 'Порядковый номер', class: 'form-label') %>
        <%= form.text_field(:order, class: 'form-control') %>
      </div>

      <%= form.submit('Отправить', class: 'btn btn-primary') %>
    </div>
  <% end %>
</div>

app/views/admin/sections/edit.html.erb
<div class="container-fluid">
  <h1>Редактирование раздела</h1>

  <%= render('admin/sections/form', section: @section, url: admin_section_path(@section)) %>

  <br>

  <div>
    <%= link_to('Показать раздел', admin_section_path(@section)) %>
  </div>
</div>

app/views/admin/sections/index.html.erb
<div class="container-fluid">
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>

  <h1>Разделы</h1>

  <%= button_to('Добавить новый раздел', new_admin_section_path, method: :get, class: 'btn btn-success') %>

  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Название</th>
        <th>Описание</th>
        <th>Позиция</th>
      </tr>
    </thead>
    <% @sections.each do |section| %>
      <tr>
        <th><%= section.id %></th>
        <td><%= link_to(section.name, admin_section_path(section)) %></td>
        <td><%= section.description %></td>
        <td><%= section.order %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/admin/sections/new.html.erb
<div class="container-fluid">
  <h1>Новый раздел</h1>

  <%= render('admin/sections/form', section: @section, url: admin_sections_path) %>
</div>

app/views/admin/sections/show.html.erb
<div class="container-fluid">
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>

  <div style="display: block">
    <h1 style="display: inline-block"><%= @section.name %></h1>
    <%= link_to('Редактировать', edit_admin_section_path(@section)) %>
    <%= button_to('Удалить', admin_section_path(@section), method: :delete, class: 'btn btn-danger') %>
  </div>

  <p><b>Описание раздела:</b> <%= @section.description %></p>

  <p><b>Количество уроков в разделе:</b> <%= @section.lessons.count %></p>

  <h4>Доступные уроки:</h4>
  <table class="table">
    <thead>
      <tr>
        <th>Название урока</th>
        <th>Описание</th>
        <th>Позиция</th>
      </tr>
    </thead>
    <% @section.lessons.order(:order).each do |lesson| %>
      <tr>
        <td><%= link_to(lesson.name, admin_lesson_path(lesson)) %></td>
        <td><%= lesson.description %></td>
        <td><%= lesson.order %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/layouts/admin_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Programming Basics</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% unless current_user.nil? %>
      <header class="p-3 mb-3 border-bottom">
        <div class="container">
          <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
              <li><%= link_to('Разделы', admin_sections_path, class: 'nav-link px-2 link-secondary') %></li>
              <li><%= link_to('Уроки', admin_lessons_path, class: 'nav-link px-2 link-dark') %></li>
            </ul>

            <div class="dropdown text-end">
              <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" style="outline: none" data-bs-toggle="dropdown">
                <%= current_user.email %>
              </a>
              <ul class="dropdown-menu text-small">
                <li><%= button_to('Выход', destroy_user_session_path, class: "dropdown-item", method: :delete) %></li>
              </ul>
            </div>
          </div>
        </div>
      </header>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Programming Basics</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>